### ISSUE TITLE
ReferenceError: weakly-referenced object no longer exists when running main.py

### ISSUE THREAD

**Issue by kkawabat** [GoBig87/code-jam-6#16]
I got this error when running main.py 

>  Traceback (most recent call last):
>    File "main.py", line 57, in <module>
>      MainApp().run()
>    File "C:\Users\kkawa\AppData\Local\Programs\Python\Python38-32\lib\site-packages\kivy\app.py", line 855, in run
>      runTouchApp()
>    File "C:\Users\kkawa\AppData\Local\Programs\Python\Python38-32\lib\site-packages\kivy\base.py", line 504, in runTouchApp
>      EventLoop.window.mainloop()
>    File "C:\Users\kkawa\AppData\Local\Programs\Python\Python38-32\lib\site-packages\kivy\core\window\window_sdl2.py", line 747, in mainloop
>      self._mainloop()
>    File "C:\Users\kkawa\AppData\Local\Programs\Python\Python38-32\lib\site-packages\kivy\core\window\window_sdl2.py", line 479, in _mainloop
>      EventLoop.idle()
>    File "C:\Users\kkawa\AppData\Local\Programs\Python\Python38-32\lib\site-packages\kivy\base.py", line 339, in idle
>      Clock.tick()
>    File "C:\Users\kkawa\AppData\Local\Programs\Python\Python38-32\lib\site-packages\kivy\clock.py", line 591, in tick
>      self._process_events()
>    File "kivy\_clock.pyx", line 384, in kivy._clock.CyClockBase._process_events
>    File "kivy\_clock.pyx", line 414, in kivy._clock.CyClockBase._process_events
>    File "kivy\_clock.pyx", line 412, in kivy._clock.CyClockBase._process_events
>    File "kivy\_clock.pyx", line 154, in kivy._clock.ClockEvent.tick
>    File "kivy\_clock.pyx", line 86, in kivy._clock.ClockEvent.get_callback
>    File "C:\Users\kkawa\AppData\Local\Programs\Python\Python38-32\lib\site-packages\kivy\weakmethod.py", line 56, in is_dead
>      return self.proxy is not None and not bool(dir(self.proxy))
>  ReferenceError: weakly-referenced object no longer exists

it seems to be a common kivy issue but not really sure how to fix it. Below are some references

https://stackoverflow.com/questions/46060693/referenceerror-weakly-referenced-object-no-longer-exists-kivy-dropdown

https://stackoverflow.com/questions/49367546/kivy-weakly-referenced-object-no-longer-exists

Edit: The issue seems to be in ContentNavigationDrawer

![image](https://user-images.githubusercontent.com/9159267/72760124-0b103980-3b95-11ea-8298-00c8910e5807.png)

with all those lines commented out the weak ref error disappears.

For now as a stop gap in main.py add right after import
```
import gc
gc.disable
```

**Comment by GoBig87** [comment]
To debug issues like these I turn on and off until the error stops.  Once I find which widget is the culprit I can go in and inspect it and find out why the garbage collector is getting rid of it.  Normally its an issue in the kv language not getting an id set.

**Comment by kkawabat** [comment]
With your help I think I've isolated the problem to MyNavigationLayout()
> self.nav_bar = MyNavigationLayout()

**Comment by kkawabat** [comment]
More specifically these two lines in the MyNavigationLayout(NavigationLayout)'s __init__() in nav_drawer.py

self.content_nav_drawer = ContentNavigationDrawer(self)

toolbar.left_action_items = [['menu', lambda x: self.toggle_nav_drawer()]]

**Comment by GoBig87** [comment]
disabling the garbage collector fixes the issue.  Its now a temporary permeant fix
