### ISSUE TITLE
Create a calibration screen for auto morse recognizer

### ISSUE THREAD

**Issue by kkawabat** [GoBig87/code-jam-6#18]
currently the auto morse recognizer uses a fixed loudness value ([active_threshold](https://github.com/GoBig87/code-jam-6/blob/c19f5a9a0da2f0952def03cdfaaaca283b171f02/tactless-tricksters/util/utility.py#L10)) to determine what is on/off signal. It would be nice to have a screen where the person can change the loudness value to better suit their environment (i.e. make it more/less sensitive)

**Comment by GoBig87** [comment]
Added in https://github.com/GoBig87/code-jam-6/pull/30
