### ISSUE TITLE
ContentNavigationDrawer Bug with buttons disabled

### ISSUE THREAD

**Issue by foosballa91** [GoBig87/code-jam-6#22]
Might be a very simple fix, but if you click on the main screen to close the navigation drawer rather than selecting a screen via the drawer, the buttons on the welcome screen remain grayed out. Then upon opening the drawer again, they are enabled, and disabled upon selecting a screen. There must be a missing condition when we are changing states.

**Comment by GoBig87** [comment]
Fixed in PR https://github.com/GoBig87/code-jam-6/pull/27
